from PyQt5 import QtWidgets
from Help.updatedoc import Ui_MainWindow


class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setupUi(self)
        self.display()

    def display(self):
        string = '实验数据处理程序程序更新日志\n\n'
        string = string + '版本命名规范：\n'
        string = string + '    1、增加大量新功能时改变第一个数字如：        Version 1.0.0 -> Version 2.0.0\n'
        string = string + '    2、对现有功能进行优化改变第二个数字如:       Version 2.0.0 -> Version 2.1.0\n'
        string = string + '    3、对现有代码长度进行优化改变第三个数字如：   Version 2.0.0 -> Version 2.0.1\n\n'
        string = string + '版本存储规范：\n'
        string = string + '    1、每个大版本最多不超过3个小版本包\n'
        string = string + '    2、最多存储3个大版本包\n\n'
        string = string + 'Version 4.0.0 Date：2020/08/22\n'
        string = string + '    1、将代码上传到Github上以便多人协同'
        string = string + '    2、新增了高级绘图功能,包括三维散点图，三维曲线图，三维曲面图\n'
        string = string + '    3、新建了分支,用于两个人单独开发\n'
        string = string + '    4、新建了相应的GUI界面以及入口界面的功能按钮\n'
        string = string + '    5、大部分功能仍然在调试之中\n\n'
        string = string + 'Version 3.1.0 Date：2020/08/\n'
        string = string + '    1、入口界面新增了点击后图标变灰的功能\n'
        string = string + '    2、修改了放大倍数出现由于python计算精度导致的小数问题\n'
        string = string + '    3、对按钮进行了大幅改进，点击按钮后会有动画效果，会显示运行情况，灰色代表正在运行\n'
        string = string + '    4、修改了坐标旋转功能，不再输入，直接在可选功能里选择需要的角度即可，共提供了9个角度可供选择\n'
        string = string + '    5、绘图功能改为直接显示在GUI界面中，可以通过可选功能选择单独显示，默认嵌入式显示\n'
        string = string + '    6、新增了导出图片功能，默认存于result文件夹中\n'
        string = string + '    7、修改了误差计算的bug，误差计算的标准值不应该出现0\n'
        string = string + '    8、修改了频率计算的bug，频率计算不应该出现0的数据\n'
        string = string + '    9、修改了放大倍数的bug，放大倍数的初始值不应该出现0\n'
        string = string + '    10、修改了计算模式历史记录的bug\n\n'
        string = string + 'Version 3.0.0 Date：2020/08/08\n'
        string = string + '    1、增加了说明文档和更新日志，直接嵌入程序之中\n'
        string = string + '    2、更改了入口界面的大小，以更加适合当前的界面功能（因为在上方加了一个任务栏）\n'
        string = string + '    3、圆角画了所有图标和输入窗口\n'
        string = string + '    4、支持了自由选择是否去掉入口界面\n'
        string = string + '    5、入口界面也加入了使用说明和更新日志\n'
        string = string + '    6、绘图时支持了绘制网格线的功能\n'
        string = string + '    7、绘制时支持了在数据点显示数据标签的功能\n'
        string = string + '    8、支持了夜晚问候语\n'
        string = string + '    9、支持了在不同节日显示不同的入口背景图片\n'
        string = string + '    10、优化了绘图和拟合的历史记录功能，旧的历史记录不再删除，同时修改了之前的bug\n'
        string = string + '    11、新增了支持横坐标用中文绘制的功能，此时必须按顺序输入\n'
        string = string + '    12、绘图时支持了自由选择是否需要legend,注意要用legend必须再可选功能处勾选\n'
        string = string + '    13、新增中文绘制时rotation可以自选的功能\n'
        string = string + '    14、增加了频率和角速度计算功能\n'
        string = string + '    15、增加了放大倍数计算功能\n\n'
        string = string + 'Version 2.1.1 Date：2020/07/30\n'
        string = string + '    1、修复了绘图模式清零时曲线条数不清零的bug\n'
        string = string + '    2、修改了一些表述错误\n'
        string = string + '    3、优化了界面的颜色配置\n\n'
        string = string + 'Version 2.1.0 Date：2020/7/28\n'
        string = string + '    1、修复了之前拟合模式结果历史记录不显示的问题\n'
        string = string + '    2、新增了excel可以自选读取的行列的功能\n'
        string = string + '    3、修复了之前excel读取的一些bug\n'
        string = string + '    4、修改了计算模式的图标\n'
        string = string + '    5、优化了绘图的颜色选择\n\n'
        string = string + 'Version 2.0.0\n'
        string = string + '    1、增加了历史记录的功能\n'
        string = string + '    2、增加了在图像绘制时自动更换颜色，以便在一幅图中绘制多条曲线用于对比（最好不要超过5条）\n'
        string = string + '    3、在程序的入口处增加了欢迎问候语和显示当前时间\n'
        string = string + '    4、增加了绝对误差和相对误差的计算(默认前一半为标准值，后一半为实际值)\n'
        string = string + '    5、增加了txt文件的自动读取,默认第一列为x，第二列为y\n'
        string = string + '    6、增加了excel文件的自动读取，默认第一列为x，第二列为y,只支持读取一个sheet，既没必要也不需要支持读取多个sheet，默认从第二行开始读取\n\n'
        string = string + 'Version 1.0.0\n'
        string = string + '    完成了初步构想的功能，是发行的最初始的版本\n\n'
        self.updatelogdisplay.setText(string)
